CQCL/pytket-extensions

.github/workflows/issue.yml
According to https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues this will only be triggered if the workflow file is on the default branch, so I can't think of a good way to test it before merging.
(The necessary secrets have been added to the repo.)
=> Add workflow to create Jira task when new issue created.

modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/tests/backend_test.py, modules/pytket-braket/tests/pytest.ini
* Switch to Aspen-9 for remote tests.
* Don't call `cancel` on completed tasks.
* Ignore some deprecation warnings.
=> [pytket-braket] Fix tests.

modules/pytket-aqt/tests/backend_test.py, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/pytket/extensions/braket/braket_convert.py, modules/pytket-braket/tests/backend_test.py, modules/pytket-cirq/tests/test_cirq_backend.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py, modules/pytket-honeywell/tests/backend_test.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq_convert.py, modules/pytket-ionq/tests/backend_test.py, modules/pytket-projectq/pytket/extensions/projectq/backends/projectq_backend.py, modules/pytket-projectq/pytket/extensions/projectq/projectq_convert.py, modules/pytket-projectq/tests/projectq_backend_test.py, modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py, modules/pytket-pyquil/tests/pyquil_convert_test.py, modules/pytket-pyquil/tests/qvm_backend_test.py, modules/pytket-pyzx/tests/pyzx_convert_test.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/result_convert.py, modules/pytket-qiskit/tests/backend_test.py, modules/pytket-qiskit/tests/qiskit_backend_test.py, modules/pytket-qiskit/tests/qiskit_convert_test.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py, modules/pytket-qulacs/pytket/extensions/qulacs/qulacs_convert.py, modules/pytket-qulacs/tests/test_qulacs_backend.py, modules/pytket-qulacs/tests/test_qulacs_convert.py
Requires numpy >= 0.20 to pass mypy checks; this should always be the case on the CI.
=> Remove "type: ignore" annotation when importing numpy.

modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
This allows noise models to be added to unitary gates, as the gate name matches the label.
=> [pytket-qiskit] match unitary gate labels to gate name

modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py, modules/pytket-qulacs/tests/pytest.ini
After the next pytket release we can omit the parameter altogether. Meanwhile set it to `False` to avoid warnings.
=> [pytket-qulacs] Don't warn for no measures. [TKET-1203]

modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py, modules/pytket-cirq/pytket/extensions/cirq/cirq_convert.py, modules/pytket-cirq/tests/cirq_convert_test.py, modules/pytket-cirq/tests/test_cirq_backend.py
Previously qubits that had no operations were not included in simulated results - this behaviour has now been changed.
In the tk_to_cirq conversion, if a qubit has no operation in the pytket circuit then it would not be present in the cirq circuit. cirq circuit objects have no 'qubits' attribute, the cirq circuit all_qubits method actually iterates through all moments, creating a frozenset of all qubits it encounters in gates. Therefore, to "add a qubit" to a circuit that has no operations, an identity gate must be added to the circuit.
To do so without tampering with the tk_to_cirq conversion code, for the moments simulators a copy of the pytket circuit for simulating is taken and identity gates are added to all qubits. When the cirq circuit is produced, even gates without any other …
=> [pytket-cirq] Update Cirq DensityMatrix/State simulators to include all circuit qubits

modules/pytket-qiskit/_metadata.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/setup.py
Requires a small change to how we construct qiskit Pauli operators.
Closes #47.
=> Support qiskit 0.25.

modules/pytket-qiskit/tests/qiskit_backend_test.py, modules/pytket-qiskit/tests/qiskit_convert_test.py, modules/pytket-qiskit/tests/test-requirements.txt
* Rewrite one test to use `PauliSumOp` instead of `WeightedPauliOperator`.
* Remove a test that uses algorithms no longer provided by qiskit (the `TketBackend` is tested elsewhere so hopefully we don't lose much by doing this).
Closes #15.
=> [pytket-qiskit] Stop using aqua in tests.

modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py
_CirqSampleBackend always requires a number of shots regardless of how results are produced.
For other backends where this is the case, the `process_circuits` method will raise a ValueError if n_shots is not set, or is set inappropriately. 
Currently _CirqSampleBackend does not do this, but Isobel has correctly pointed out that it probably should.
So now it does.
=> [bugfix][pytket-cirq][tket-1240] Raise ValueError if n_shots not appropriate for _CirqSampleBackend

modules/pytket-aqt/pytket/extensions/aqt/backends/aqt.py, modules/pytket-aqt/tests/convert_test.py, modules/pytket-aqt/tests/test-requirements.txt
The rebase to the AQT gate set was wrong, for both single qubit and two qubit replacements.
=> [pytket-aqt][bugfix] Fixed RebaseAQT

modules/pytket-qiskit/tests/backend_test.py
The order is irrelevant, and with recent changes on pytket develop branch this test currently fails because the coupling is stored in a different order.
=> [pytket-qiskit] Test equality of sets.

modules/pytket-cirq/_metadata.py, modules/pytket-cirq/setup.py
=> [pytket-cirq] [hotfix] Make cirq version requirement more strict.

docs/requirements.txt
This PR should fix #84.
In Sphinx autodoc v4.0.1, if a program mutate `sys.meta_path` then the `sys.meta_path.remove(finder)` in this [line](https://github.com/sphinx-doc/sphinx/blob/bdce720bb9f69d1c39ed14d214e15db4df341805/sphinx/ext/autodoc/mock.py#L151) might fail (raise a ValueError). Unfortunately, Cirq 0.11.0 does [exactly](https://github.com/quantumlib/Cirq/blob/58e16054159af6719825ada1d477b3b6d95204c5/cirq-core/cirq/_compat.py#L557) that to handle depracated modules.
This PR uses a [forked](https://github.com/yao-cqc/sphinx/blob/7691d43d0aebe1f339e4bd2704d2237295507fa1/sphinx/ext/autodoc/mock.py#L151) Sphinx v4.0.1 that ignores the exception rased by `sys.meta_path.remove(finder)`. Not removing the mock finders should only affect the speed of importing modules. (i.e. the …
=> Using a forked sphinx 4.0.1. 

modules/pytket-qsharp/tests/azure_test.py
In one of the azure tests we were asking for shots when the backend only supports counts.
Furthermore, the ionq simulator returns counts deterministically as a (scaled, rounded) probability distribution, so change the number of shots to avoid rounding issues, and test result.
=> [pytket-qsharp] Fix azure test.

modules/pytket-braket/pytket/extensions/braket/backends/braket.py
Resolves #90.
BraketBackend can now take a `braket.aws.AwsSession` object, which itself can take a `boto3.Session` object. Since we [can pass AWS credentials to the `boto3.Session` object](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#passing-credentials-as-parameters), this means we can use BraketBackend without having credentials set as environment variables (as the AWS CLI does).
If the user doesn't pass an AwsSession object, BraketBackend behaves as it did before (with braket's internal code creating sessions as needed).
----
I've tested this using the Amazon Braket SV1 simulator in us-west-1 (without any other AWS credentials configured) and it seems to work okay. I'm not sure that it would help much to add a unit test in for this functionality as the …
=> [pytket-braket] Allow BraketBackend to take an AwsSession

.github/workflows/build-test, modules/pytket-qulacs/tests/test-requirements.txt
This prevents the problem of qulacs tests forcing a downgrade of cirq, which then has to be upgraded to run cirq tests, which then fail because the upgrade from cirq 0.10 to cirq 0.11 on Linux is broken.
=> Require version of openfermion compatible with cirq 0.11.

modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py
(Which happens to be everywhere now,)
=> Explicitly disallow non-Hermitian operators where they're not supported.

modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/tests/backend_test.py
Fixes #102. 
This matches the definition of `.device` in other Backend classes.
=> [pytket-braket] Add @property decorator to BraketBackend.device

modules/pytket-braket/pytket/extensions/braket/backends/braket.py
Resolves #106.
In `BraketBackend.circuit_status()`, we previously assumed that `self._cache[handle]` would already have been set.
This is not always the case (for example, a different BraketBackend instance could be used used to run `.process_circuits()` and `.circuit_status()`).
This change makes setting the result in the cache more robust.
=> [pytket-braket] Handle BraketBackend._cache updates robustly

modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibmq_emulator.py
Resolves #115. 
This parameter is the type that's returned by `IBMQFactory.enable_account()`. It takes the hub/group/project for a backend, but also the user's API token, and returns a provider.
Adding this as a potential way to specify a provider *and* credentials to IBMQBackend and IBMQEmulatorBackend gives a way to set up credentials that doesn't require saving them to disk, which is useful for some workflows.
As with pytket-braket, the description in the IBMQBackend docstring hopefully makes it clear that this is only useful if your credentials are not configured on your local machine.
=> [pytket-qiskit] Add optional account_provider to IBMQBackend and IBMQEmulatorBackend

modules/pytket-aqt/pytket/extensions/aqt/backends/aqt.py, modules/pytket-qsharp/pytket/extensions/qsharp/backends/azure_quantum.py
In these backends' `circuit_status()` method, we previously assumed that self._cache[handle] would already have been set.
This is not always the case (a different backend instance could be used used to run .process_circuits() and .circuit_status()).
This change makes setting the result in the cache more robust.
This is the same fix as was done in #107, but for other backends that had the same bug.
=> [pytket-aqt] [pytket-qsharp] Make AQTBackend and AzureBackend handle cache updates more robustly

.github/workflows/lint.yml, modules/pytket-ionq/_metadata.py, modules/pytket-ionq/docs/changelog.rst, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py, modules/pytket-ionq/tests/backend_test.py, modules/pytket-projectq/_metadata.py, modules/pytket-projectq/docs/changelog.rst, modules/pytket-projectq/setup.py, modules/pytket-qiskit/_metadata.py, modules/pytket-qiskit/docs/changelog.rst, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibmq_emulator.py, modules/pytket-qiskit/tests/backend_test.py
This is for a hotfix solving bug #128
All remote tests for `pytket-qiskit` and `pytket-ionq` are passing.
=> [hotfix] [pytket-qiskit] [pytket-ionq] fix #128

modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
Small API change in pytket: the `name` parameter can no longer be `None`, it must not be specified instead.
=> [pytket-qiskit] Do not pass `name=None` to `tket.Circuit()` 

docs/conf.py, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py, modules/pytket-pyquil/tests/qvm_backend_test.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/tests/backend_test.py, modules/pytket-qsharp/pytket/extensions/qsharp/backends/common.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py
Or explicitly, update pytket-qiskit, pytket-braket and pytket-pyquil to use new BackednInfo attributes instead of the characterisation bucket dictionary.
=> Update use of BackendInfo to reflect pytket/Mushroom requests

modules/pytket-qiskit/docs/changelog.rst, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py
without retrieving job (which could be slow due to retrieving results with it)
relevant qiskit docs: https://qiskit.org/documentation/_modules/qiskit/providers/ibmq/job/ibmqjob.html#IBMQJob.status
=> [pytket-qiskit] Use provider to check job status

modules/pytket-qsharp/_metadata.py, modules/pytket-qsharp/docs/changelog.rst, modules/pytket-qsharp/setup.py
Also require a corresponding version of `qsharp-core`, since `qsharp` seems not do so, which can cause errors on upgrade.
=> [pytket-qsharp] Update to qsharp 0.18.

modules/pytket-projectq/setup.py
Just hiked the requirements. I checked with [projectq's changelog](https://github.com/ProjectQ-Framework/ProjectQ/releases/tag/v0.7.0), it does not look like anything should have been broken (and the tests pass).
=> [pytket-projectq] Upgraded requirements to `projectq ~= 0.7.0`

modules/pytket-honeywell/_metadata.py, modules/pytket-honeywell/docs/changelog.rst, modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py, modules/pytket-honeywell/tests/backend_test.py
Simulator type (state-vector or stabilizer) specified on backend
initialisation, to perhaps support compilation and predicate checking in
future.
Whether to run noisy simulation specified at process_circuit time via
kwarg.
=> support new honeywell simulator options

README.md, modules/pytket-qiskit/pytket/extensions/qiskit/tket_backend.py
The old ones get redirected anyway, but we may as well have them correct.
=> Update URLs on `pytket` repo.

modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/tests/qiskit_convert_test.py
The test case is taken from the example notebook that was failing [here](https://github.com/CQCL/pytket/blob/aa994fd4ae0db771c32f4b73fb176683582f1c92/examples/python/conditional_gate_example.py#L98).
=> [pytket-qiskit] Ensure `tk_command_to_qiskit` returns an `Instruction`.

modules/base-test-requirements.txt, modules/pytket-honeywell/pytket/extensions/honeywell/__init__.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/__init__.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/api_wrappers.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/credential_storage.py, modules/pytket-honeywell/tests/api_test.py, modules/pytket-honeywell/tests/backend_test.py, modules/pytket-honeywell/tests/conftest.py, modules/pytket-qiskit/docs/changelog.rst, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/setup.py, modules/pytket-qiskit/tests/qiskit_backend_test.py, modules/pytket-qiskit/tests/qiskit_convert_test.py
This PR enables the `HoneywellQAPI` api wrapper to optionally store credentials (password, id_token and refresh_token) in memory as opposed to in persistent storage via `keyring`. Persistent storage is used by default.
I've done reasonably thorough manual testing, but haven't added any `pytest` tests as testing credential-related features doesn't appear to be standard across the pytket-extensions. Very happy to make any desired changes.
=> [feature][pytket-honeywell] Add option to store credentials in memory.

.github/workflows/docs/build-docs
We were getting incorrect module names at the top of the sidebar on the docs pages. This fixes that.
=> Avoid shadowing variable name in loop.

modules/pytket-aqt/setup.py, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/setup.py, modules/pytket-cirq/setup.py, modules/pytket-honeywell/setup.py, modules/pytket-ionq/setup.py, modules/pytket-projectq/setup.py, modules/pytket-pyquil/setup.py, modules/pytket-pyzx/setup.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/setup.py, modules/pytket-qsharp/setup.py, modules/pytket-qulacs/setup.py, modules/pytket-stim/setup.py
* Update pytket dependency to 0.18.0rc0;
* pytket-qiskit can go back to using `FullyConnected` instead of a custom `FullyConnected2`;
* pytket-braket should not use `FullyConnected` since it doesn't support coupling maps (use normal `Architecture` instead).
=> Use `FullyConnected` connectivity graph.

.github/workflows/docs/requirements.txt
resolves #89 
The issue that let us use the forked sphinx has been fixed by this [pr](https://github.com/quantumlib/Cirq/commit/9349802d924bb5d23753fe0e30e396e0ec84af38) since Cirq 0.13.0
=> Use released sphinx for building docs

.github/CODEOWNERS, .github/workflows/build-test, .github/workflows/build_and_test.yml, README.md, modules/pytket-iqm/MANIFEST.in, modules/pytket-iqm/README.md, modules/pytket-iqm/_metadata.py, modules/pytket-iqm/docs/api.rst, modules/pytket-iqm/docs/changelog.rst, modules/pytket-iqm/docs/intro.txt, modules/pytket-iqm/pytket/extensions/iqm/__init__.py, modules/pytket-iqm/pytket/extensions/iqm/backends/__init__.py, modules/pytket-iqm/pytket/extensions/iqm/backends/config.py, modules/pytket-iqm/pytket/extensions/iqm/backends/demo_settings.json, modules/pytket-iqm/pytket/extensions/iqm/backends/iqm.py, modules/pytket-iqm/setup.py, modules/pytket-iqm/tests/backend_test.py, modules/pytket-iqm/tests/convert_test.py, modules/pytket-iqm/tests/test-requirements.txt
Tested only on the "demo" device (which is not a simulator but just produces pseudo-random bits). Other devices may be specified by passing parameters to the `IQMBackend` constructor. Credentials (`username` and `api_key`) may be stored in the pytket config file (with the key `iqm`), or passed directly to the constructor.
=> Add IQM extension

modules/pytket-aqt/pytket/extensions/aqt/backends/aqt.py, modules/pytket-aqt/setup.py, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/setup.py, modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py, modules/pytket-cirq/setup.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py, modules/pytket-honeywell/setup.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq_convert.py, modules/pytket-ionq/setup.py, modules/pytket-iqm/pytket/extensions/iqm/backends/iqm.py, modules/pytket-iqm/setup.py, modules/pytket-projectq/pytket/extensions/projectq/backends/projectq_backend.py, modules/pytket-projectq/setup.py, modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py, modules/pytket-pyquil/setup.py, modules/pytket-pyzx/setup.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/setup.py, modules/pytket-qiskit/tests/backend_test.py, modules/pytket-qsharp/pytket/extensions/qsharp/backends/common.py, modules/pytket-qsharp/setup.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py, modules/pytket-qulacs/setup.py, modules/pytket-stim/pytket/extensions/stim/backends/stim_backend.py, modules/pytket-stim/setup.py
A consistent part of compiling to different hardware is rebasing a circuit i.e. rewriting each gate in a circuit so that is a (sequence) of gates with OpType permitted by the hardware.
Currently this is completed inconsistently across all Backend. Each Backend now has a `rebase_pass` method which returns a `BasePass` object for applying to a Circuit to complete this transformation. This is also a new abstractmethod of the base `Backend` class.
=> Update Backend objects to use rebase_pass abstract method

modules/pytket-qsharp/_metadata.py, modules/pytket-qsharp/docs/changelog.rst, modules/pytket-qsharp/setup.py
I checked to see if #180 or #268 were fixed. Neither is. (The problem for both seems to be qsharp's dependence on an old version of pyzmq.)
=> [pytket-qsharp] Update to qsharp 0.22.

.github/workflows/hotfix.yml
Basically copy-and-pasted from `build_and_test.yml`. (Maybe in future we could combine the YAML files into one.)
=> Publish wheels to pypi from hotfix workflow

modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py
Fixes [TKET-1767](https://cqc.atlassian.net/browse/TKET-1767?atlOrigin=eyJpIjoiOWY1ODIyYzM3NjAyNDFiNmEyMjFkYjFkODI0MjBmOTUiLCJwIjoiaiJ9).
This PR addresses the returned error while running `to_dict()` on the underlying `BackendInfo`. It originates from the `characterisation` [keys](https://github.com/CQCL/pytket-extensions/blob/eebdaf261cb99d4cfc7d4622aa708bd6b26aea19/modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py#L446)  returning a `defaultdict` type which errors the `asdict` from `dataclasses`. 
Bug fix: Cast the `dict` type when filtering `characterisation` keys to keep [here](https://github.com/CQCL/pytket-extensions/blob/eebdaf261cb99d4cfc7d4622aa708bd6b26aea19/modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py#L452).
=> [TKET-1767] Cast the dict type to avoid error while running to_dict on BackendInfo.

modules/pytket-aqt/pytket/extensions/aqt/backends/aqt.py, modules/pytket-aqt/setup.py, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/setup.py, modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py, modules/pytket-cirq/setup.py, modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py, modules/pytket-honeywell/setup.py, modules/pytket-honeywell/tests/convert_test.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq_convert.py, modules/pytket-ionq/setup.py, modules/pytket-iqm/pytket/extensions/iqm/backends/iqm.py, modules/pytket-iqm/setup.py, modules/pytket-projectq/pytket/extensions/projectq/backends/projectq_backend.py, modules/pytket-projectq/pytket/extensions/projectq/projectq_convert.py, modules/pytket-projectq/setup.py, modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py, modules/pytket-pyquil/setup.py, modules/pytket-pyzx/setup.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py, modules/pytket-qiskit/setup.py, modules/pytket-qsharp/pytket/extensions/qsharp/backends/common.py, modules/pytket-qsharp/pytket/extensions/qsharp/backends/toffoli.py, modules/pytket-qsharp/setup.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py, modules/pytket-qulacs/setup.py, modules/pytket-stim/pytket/extensions/stim/backends/stim_backend.py, modules/pytket-stim/setup.py
* use auto_squash and auto_rebase
* provide full gateset as one argument to RebaseCustom
* remove use of Rebase<Target> passes
requires changes from
https://github.com/CQCL/tket/pull/234
and
https://github.com/CQCL/tket/pull/214
=> [bugfix] update rebases and squash to new pytket API

modules/pytket-aqt/setup.py, modules/pytket-braket/_metadata.py, modules/pytket-braket/docs/changelog.rst, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/setup.py, modules/pytket-braket/tests/backend_test.py, modules/pytket-cirq/setup.py, modules/pytket-honeywell/setup.py, modules/pytket-ionq/setup.py, modules/pytket-iqm/setup.py, modules/pytket-projectq/setup.py, modules/pytket-pyquil/setup.py, modules/pytket-pyzx/setup.py, modules/pytket-qiskit/setup.py, modules/pytket-qiskit/tests/backend_test.py, modules/pytket-qsharp/setup.py, modules/pytket-qulacs/setup.py, modules/pytket-stim/setup.py
Fix up a pytket-qiskit test.
Also add "region" argument to `BraketBackend` constructor and fix up tests following retirement of Aspen-11.
(I tried adding a test for the new OQC device, but it didn't like the ARN; this will need to be investigated separately.)
=> Require pytket 1.0.0rc14

modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py, modules/pytket-honeywell/tests/api_test.py
HQS (and pytket-honeywell) now allow users to submit to a 'device family' ("HQS-LT") instead of specifying the exact device they want to run on.
We checked with the developers of the HQS API and it turns out that if jobs are submitted to a device family and batching is requested in the request JSON then an error will be returned (as the circuits may be run on different machines).
This PR removes the insertion of default batch params in the case that the user is submitting to a device family. If a user manually inserts batch params then they the API will still return an error, which I figured should be the correct behaviour.
=> Remove default batch params if submitting to HQS family device.

.github/workflows/build_and_test.yml
Because 3.9 is the only version where all extensions are supported.
=> Build with 3.9, not 3.10, in release workflow.

modules/pytket-quantinuum/docs/changelog.rst, modules/pytket-quantinuum/docs/intro.txt, modules/pytket-quantinuum/pytket/extensions/quantinuum/__init__.py, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/__init__.py, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/api_wrappers.py, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/credential_storage.py, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py, modules/pytket-quantinuum/setup.py, modules/pytket-quantinuum/tests/api1_test.py, modules/pytket-quantinuum/tests/api_test.py, modules/pytket-quantinuum/tests/backend_test.py, modules/pytket-quantinuum/tests/conftest.py, modules/pytket-quantinuum/tests/convert_test.py
This is motivated by a couple of major factors:
* Storing passwords unencrypted is bad
* `keyring` is a difficult package to use cross platform as it requires
platform specific backends
* JWT id tokens expire quickly
Previously we would store id and refresh tokens using keyring. In theory
if an in date refresh token exists that is used to retrive a new ID
token. A frequent user would only have to log in once.
When this proved unstable we added the ability to also store your
password in keyring, and just recommended against it.
When this also proved unstable we added hack upon hack and recommended
frequent clearing of credentials and retries.
This PR aims to simplify this by requiring a log in for each session.
Username/email can be stored in pytket config and so will not be
requested each …
=> [pytket-quantinuum] simplify quantinuum auth and remove unused API methods

modules/pytket-braket/pytket/extensions/braket/backends/braket.py
Result object is None if the task fails.
If fail would like it to return the failureReason from Braket
https://github.com/aws/amazon-braket-sdk-python/blob/v1.16.0/src/braket/aws/aws_quantum_task.py#L286-L288
Also is the same in latest versions as well
=> fix braket task failure status reason

.github/workflows/lint.yml, modules/pytket-cirq/tests/cirq_convert_test.py, modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/tests/qiskit_convert_test.py
Fixes #147 
This PR addresses the bug of converting a barrier optype defined over classical bits to Qiskit. It turns out that Qiskit doesn't support `Barrier` for bits. An error is raised in that case.
=> #147 Fix barrier conversion to qiskit

modules/pytket-cirq/_metadata.py, modules/pytket-cirq/docs/changelog.rst, modules/pytket-cirq/pytket/extensions/cirq/cirq_convert.py, modules/pytket-cirq/setup.py, modules/pytket-cirq/tests/cirq_convert_test.py
Also a change to the type signature of `process_characterisation()`.
Closes #339 .
=> [pytket-cirq] Update to cirq 0.14; replace use of deprecated method and device.

.github/workflows/build_and_test.yml
Fix the bug introduced with #362 where the `buid_and_test.yml` fails if a PR has no changes to pytket extensions.
=> Skip checks for PRs with no pytket extension changes

modules/pytket-braket/docs/changelog.rst, modules/pytket-braket/pytket/extensions/braket/backends/braket.py, modules/pytket-braket/pytket/extensions/braket/braket_convert.py, modules/pytket-braket/tests/backend_test.py, modules/pytket-braket/tests/convert_test.py
Fixes #375 .
Currently we ignore measurement operations in tket circuits, since braket automatically measures everything. But we need to be able to handle circuits where not all qubits are measured. Here we keep track of the measurement mappings in a dictionary encoded in the result handle.
=> [pytket-braket] Handle measurements.

modules/pytket-quantinuum/docs/changelog.rst, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py, modules/pytket-quantinuum/tests/backend_test.py
cost_estimate now requires a login to the API
the only questionable part is that the method automatically tries to use the right syntax checker backend for the backend currently in use.
=> [pytket-quantinuum] use syntax checkers for cost estimate

modules/pytket-ionq/docs/changelog.rst, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py, modules/pytket-ionq/pytket/extensions/ionq/backends/ionq_convert.py, modules/pytket-ionq/tests/backend_test.py
follow on for https://github.com/CQCL/pytket-extensions/pull/346
Use the Ionq  API to retrieve relevant device info
this now means authentication is required to initialise the backend so update use of machine debug to compensate.
=> [feature] [pytket-ionq] use api for ionq device info

modules/pytket-braket/pytket/extensions/braket/backends/braket.py
When doing constant polling for status there is an additional status which is not handled by StatusEnum.Cancelled 
Which ends up being handled by this [line](https://github.com/CQCL/pytket-extensions/blob/develop/modules/pytket-braket/pytket/extensions/braket/backends/braket.py#L768)
`Unrecognized state 'CANCELLING'`
Let me know if you'd like other behavior in handling this status.
Thanks!
=> [pytket-braket] add additional cancelling status for braket

modules/pytket-braket/pytket/extensions/braket/backends/braket.py
To fix issue related to Lucy backend _all_qubits issue reference in #382.
self._all_qubits
```
[0, 1, 2, 4, 6, 7]
```
Missing the 3 and 5.
This causes issues with the conversion to braket circuit via this [method](https://github.com/CQCL/pytket-extensions/blob/develop/modules/pytket-braket/pytket/extensions/braket/backends/braket.py#L635)
When getting measures back from the results will only have the 6 qubits rather than 8 qubits for the samples.
Solution pulls all nodes in connectivity graph flattens them and then uses the set operator to get unique ordered list.
Now should return
self._all_qubits
```
[0, 1, 2, 3, 4, 5, 6, 7]
```
Please let me know if there is anything I can do
=> [pytket-braket] fix  _all_qubits for Lucy

modules/pytket-cirq/setup.py
=> [pytket-cirq] [bugfix] Require protobuf < 4.0.

modules/pytket-pyquil/setup.py
Solves https://github.com/CQCL/pytket/issues/153 by allowing pyjwt 2.4 to be installed with pytket-pyquil.
=> Remove constraint on qcs-api-client.

modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py
Some of the Myqos services do not allow for nested asynio event loops, this PR enables a `use_websocket` flag to be passed by the user for the `cost` and `circuit_status` methods in QuantinuumBackend, which disables using asyncio where neccessary.
=> Add `use_websocket` kwarg to pytket-quum /cost flow

modules/pytket-quantinuum/docs/changelog.rst, modules/pytket-quantinuum/docs/intro.txt, modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py, modules/pytket-quantinuum/tests/api1_test.py, modules/pytket-quantinuum/tests/backend_test.py
The Quantinuum batching system is not  a good fit for process_circuits as an interface, and the way of doing it with keyword arguments was getting cumbersome. This simplifies things, at the cost of no longer matching a generic interface. It also fixes an existing bug where one could not start a batch by submitting just a single circuit.
=> [feature] [pytket-quantinuum] add new simpler batching interface

modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/tests/qiskit_convert_test.py
As pointed out in the #tket-support channel `tk_to_qiskit` was failing for CRx and CRy operations. I have now added these to qiskit_convert.py to fix this.
I don't think there is any reason why these were left out but correct me if I'm wrong.
I have moved CRy fron `_qiskit_gates_other` to `_qiskit_gates_2q` is this the right place for it?
There is also a comment here about the CnRy which is probably irrelevant to this.
```
One way mapping: CRY is a special case of CnRy, but not vice versa.
Constructing a qiskit CnRy gate is not just a single step,
so treat as a special case.
del _known_qiskit_gate_rev[OpType.CnRy]
```
=> add CRx and CRy

modules/pytket-qiskit/docs/changelog.rst, modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py, modules/pytket-qiskit/tests/qiskit_convert_test.py
At the moment, attempting to convert a tket circuit containing `ecr` gates (one of the basis gates in OQC's quantum computers) to a qiskit circuit (via the `tk_to_qiskit` method) raises the following error
```console
NotImplementedError: Cannot convert tket Op to Qiskit gate: ECR
```
This simple PR fixes the underlying issue by adding the `ECRGate` to the `_qiskit_gates_2q` list in the qiskit converter.
As a result, circuits compiled to the OQC device using tket can be translated to Qiskit without errors.
=> Support ECRGate in `pytket-qiskit` circuit conversion

modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py, modules/pytket-cirq/tests/test_cirq_backend.py, modules/pytket-pysimplex/pytket/extensions/pysimplex/backends/simplex_backend.py, modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py, modules/pytket-stim/pytket/extensions/stim/backends/stim_backend.py
QulacsBackend and the Cirq backends previously had the `backend_info` property set as `None`, and StimBackend and SimplexBackend did not have the `backend_info` property set at all.
This PR makes the `.backend_info` property of these backends return `BackendInfo` instances that have the name, extension version and gatesets set. (The other properties aren't very useful for locally-run simulators, as far as I can tell, so I've not set them.)
=> Add missing backend info for Qulacs / Cirq / PySimplex / Stim backends

.github/workflows/build-test, modules/pytket-qsharp/README.md, modules/pytket-qsharp/_metadata.py, modules/pytket-qsharp/docs/changelog.rst, modules/pytket-qsharp/docs/intro.txt, modules/pytket-qsharp/pytket/extensions/qsharp/qsharp_convert.py, modules/pytket-qsharp/setup.py
=> Update to qsharp 0.26; enable Windows/3.10 support and MacOS/3.10 tests
