CQCL/pytket-extensions

- .github/workflows/issue.yml
Include title and full URL. Actually tested this time on another repo.
The angle quotation marks are because I can't seem to use either `'` or `"` here (and I like to think they add a certain style...).
> Improve Jira task creation.

- modules/pytket-qiskit/tests/backend_test.py
This test is practically impossible to run, and doesn't test much anyway.
> [pytket-qiskit] Delete test. Fixes #18

- modules/pytket-qiskit/tests/backend_test.py
> [pytket-qiskit] Modify test (now that athens supports mid-circuit measurements).

- docs/conf.py
- docs/requirements.txt
- modules/pytket-cirq/docs/index.rst
- modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py
> Document cirq backends.

- .github/workflows/build_and_test.yml
- .github/workflows/docs.yml
- .github/workflows/hotfix.yml
- modules/pytket-qsharp/setup.py
> [pytket-qsharp] Update qsharp dependency and remove workaround for issue that has gone away.

- modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py
- modules/pytket-qiskit/tests/backend_test.py
Also use fixtures in the backend_test to only construct the backend once (which is a network limited step).
> Correct phase error in IBM rebase and support symbolic angles.

- modules/pytket-aqt/tests/backend_test.py
- modules/pytket-aqt/tests/convert_test.py
- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
- modules/pytket-braket/tests/backend_test.py
- modules/pytket-honeywell/pytket/extensions/honeywell/backends/api_wrappers.py
- modules/pytket-honeywell/tests/backend_test.py
- modules/pytket-ionq/tests/backend_test.py
- modules/pytket-qiskit/tests/backend_test.py
- modules/pytket-qsharp/tests/azure_test.py
> Use pytket config for credentials in tests.

- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/tests/qiskit_convert_test.py
Qiskit Parameter generates a uuid upon creation that is used for equality checks. In order to bind original parameters to those after a qiskit -> tket -> qiskit conversion round trip, we optionally allow the preservation of this UUID in the name of the tket symbol, as a "_UUID:<uuid>" addendum to the name. This has two consequences worth noting:
* Reservation of the "_UUID:" substring for internal use in tket symbol names.
* If the preservation is used, the tket -> qiskit -> tket round trip will not preserve symbol names.
> [pytket-qiskit] Optionally allow preserving parameter uuid. Closes #72.

- .github/workflows/lint.yml
Otherwise it won't be run on PRs from forked repos.
> Run lint check on PRs.

- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/tests/qiskit_convert_test.py
Add some minor infrastrcuture to support gates equivalent up to global phase
> [bugfix] [TKET-1336] [pytket-qiskit] support V gate

- modules/pytket-qiskit/_metadata.py
- modules/pytket-qiskit/docs/changelog.rst
- modules/pytket-qiskit/setup.py
> Update qiskit version to 0.27.

- modules/pytket-projectq/_metadata.py
- modules/pytket-projectq/docs/changelog.rst
- modules/pytket-projectq/setup.py
> [pytket-projectq] Update projectq dependency to 0.6.

- modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py
- modules/pytket-ionq/tests/backend_test.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibmq_emulator.py
- modules/pytket-qiskit/tests/backend_test.py
> [bugfix] [pytket-qiskit] [pytket-ionq] AerBackend does not respect n_shots list

- modules/pytket-aqt/MANIFEST.in
- modules/pytket-braket/MANIFEST.in
- modules/pytket-cirq/MANIFEST.in
- modules/pytket-honeywell/MANIFEST.in
- modules/pytket-ionq/MANIFEST.in
- modules/pytket-projectq/MANIFEST.in
- modules/pytket-pyquil/MANIFEST.in
- modules/pytket-pyzx/MANIFEST.in
- modules/pytket-qiskit/MANIFEST.in
- modules/pytket-qsharp/MANIFEST.in
- modules/pytket-qulacs/MANIFEST.in
> Add `py.typed` files to extension modules.

- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
> [pytket-braket] Update `characterisation` implementation to reflect new `BackendInfo`.

- modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py
- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/pytket/extensions/qiskit/result_convert.py
- modules/pytket-qiskit/pytket/extensions/qiskit/tket_backend.py
- modules/pytket-qiskit/pytket/extensions/qiskit/tket_job.py
- modules/pytket-qiskit/setup.py
- modules/pytket-qiskit/tests/backend_test.py
- modules/pytket-qiskit/tests/qiskit_convert_test.py
- modules/pytket-qiskit/tests/test-requirements.txt
Closes #152 
Closes #169 
See individual commits
> [pytket-qiskit] pytket 0.14rc0, qiskit 0.29, deprecation warnings

- modules/pytket-qulacs/_metadata.py
- modules/pytket-qulacs/docs/changelog.rst
- modules/pytket-qulacs/setup.py
> [pytket-qulacs] Update qulacs requirement and bump pytket-qulacs version.

- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
- modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py
- modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py
- modules/pytket-qsharp/pytket/extensions/qsharp/backends/azure_quantum.py
Thanks to better typing in pytket, these cast should become superfluous in the next release.
> [all] [typing] Remove superfluous casts

- .github/workflows/build_and_test.yml
Test run for all modules: https://github.com/CQCL/pytket-extensions/runs/3607930080
This is the new `macos-latest`: https://github.com/actions/virtual-environments/issues/4060
> Test on MacOS 11.

- modules/pytket-qiskit/_metadata.py
- modules/pytket-qiskit/docs/changelog.rst
- modules/pytket-qiskit/setup.py
- modules/pytket-qiskit/tests/backend_test.py
> [pytket-qiskit] Update to qiskit 0.30.

- modules/pytket-qiskit/pytket/extensions/qiskit/tket_job.py
- modules/pytket-qiskit/tests/qiskit_backend_test.py
The following commits solve the immediate problem described in the related issue. However, the [qiskit-integration](https://github.com/CQCL/pytket/blob/main/examples/qiskit_integration.ipynb) notebook is still failing as far as I can tell (for another reason now)
I will keep you udpated.
> [pytket-qiskit] [bugfix] Fix #195

- modules/pytket-qsharp/_metadata.py
- modules/pytket-qsharp/docs/changelog.rst
- modules/pytket-qsharp/setup.py
> Update to qsharp 0.19.

- .github/workflows/docs.yml
- modules/pytket-honeywell/docs/changelog.rst
- modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py
I accidentally broke it with #204 .
Also fix a couple of formatting issues.
> Fix scheduled docs build.

- .github/workflows/build_and_test.yml
- README.md
- docs/conf.py
- modules/pytket-qsharp/README.md
To here: https://cqcl.github.io/pytket-extensions/doc/index.html
> Publish extensions docs from release workflow.

- modules/pytket-cirq/_metadata.py
- modules/pytket-cirq/docs/changelog.rst
- modules/pytket-cirq/setup.py
> [pytket-cirq] Update cirq requirement to 0.13.

- modules/pytket-qsharp/_metadata.py
- modules/pytket-qsharp/docs/changelog.rst
- modules/pytket-qsharp/setup.py
> Update to qsharp 0.20.

- modules/pytket-qiskit/setup.py
Solves https://github.com/CQCL/pytket-extensions/issues/241
Upgrade to qiskit 0.32.0
> upgrade to qiskit 0.32.0

- modules/pytket-qsharp/_metadata.py
- modules/pytket-qsharp/docs/changelog.rst
- modules/pytket-qsharp/setup.py
> Update qsharp to 0.21.

- modules/pytket-cirq/pytket/extensions/cirq/cirq_convert.py
- modules/pytket-cirq/tests/cirq_convert_test.py
I needed this for some of my work. Might as well merge it in.
> [feature] [pytket-cirq] Added support for cirq.ops.ParallelGate

- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/tests/qiskit_convert_test.py
> Fix return value of `append_tk_command_to_qiskit` for TK1 operations.

- modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py
- modules/pytket-honeywell/tests/backend_test.py
~waiting for Honeywell to enable for our accounts~
> [feature] [pytket-honeywell] use batching in process_circuits

- .github/workflows/build_and_test.yml
> Build docs with Python 3.9.

- .github/workflows/build-test
- modules/pytket-qiskit/docs/intro.txt
- modules/pytket-qiskit/setup.py
> [pytket-qiskit] Test on Windows with Python 3.10

- modules/pytket-aqt/setup.py
- modules/pytket-braket/setup.py
- modules/pytket-cirq/setup.py
- modules/pytket-honeywell/setup.py
- modules/pytket-ionq/setup.py
- modules/pytket-iqm/setup.py
- modules/pytket-projectq/setup.py
- modules/pytket-pyquil/setup.py
- modules/pytket-pyzx/setup.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py
- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/setup.py
- modules/pytket-qiskit/tests/backend_test.py
- modules/pytket-qsharp/setup.py
- modules/pytket-qulacs/setup.py
- modules/pytket-stim/setup.py
> Make backendinfo JSON-serializable

- modules/pytket-aqt/setup.py
- modules/pytket-braket/setup.py
- modules/pytket-cirq/setup.py
- modules/pytket-honeywell/setup.py
- modules/pytket-ionq/setup.py
- modules/pytket-iqm/setup.py
- modules/pytket-projectq/setup.py
- modules/pytket-pyquil/setup.py
- modules/pytket-pyzx/setup.py
- modules/pytket-qiskit/setup.py
- modules/pytket-qsharp/setup.py
- modules/pytket-qulacs/setup.py
- modules/pytket-qulacs/tests/test_qulacs_backend.py
- modules/pytket-stim/setup.py
> Require pytket 1.0.0rc9; remove use of `QubitPauliOperator.from_OpenFermion` in test.

- modules/pytket-honeywell/pytket/extensions/honeywell/backends/honeywell.py
- modules/pytket-honeywell/tests/backend_test.py
- modules/pytket-honeywell/tests/convert_test.py
~HQS API NOT ACCEPTING YET~
Requires release of pytket containing changes from https://github.com/CQCL/tket/pull/193
not all H-system backends support it so requires some gate set parametrisation
compiler options also need to be set in request body
> [feature] [pytket-honeywell] support use of zzphase

- modules/pytket-pyzx/_metadata.py
- modules/pytket-pyzx/docs/changelog.rst
- modules/pytket-pyzx/setup.py
> [pytket-pyzx] Update to pyzx 0.7

- modules/pytket-aqt/setup.py
- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
- modules/pytket-braket/setup.py
- modules/pytket-cirq/pytket/extensions/cirq/cirq_convert.py
- modules/pytket-cirq/setup.py
- modules/pytket-cirq/tests/cirq_convert_test.py
- modules/pytket-honeywell/setup.py
- modules/pytket-ionq/setup.py
- modules/pytket-iqm/pytket/extensions/iqm/backends/iqm.py
- modules/pytket-iqm/setup.py
- modules/pytket-projectq/pytket/extensions/projectq/backends/projectq_backend.py
- modules/pytket-projectq/setup.py
- modules/pytket-pyquil/pytket/extensions/pyquil/backends/forest.py
- modules/pytket-pyquil/pytket/extensions/pyquil/pyquil_convert.py
- modules/pytket-pyquil/setup.py
- modules/pytket-pyzx/setup.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/aer.py
- modules/pytket-qiskit/pytket/extensions/qiskit/backends/ibm.py
- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/setup.py
- modules/pytket-qiskit/tests/backend_test.py
- modules/pytket-qsharp/pytket/extensions/qsharp/backends/common.py
- modules/pytket-qsharp/setup.py
- modules/pytket-qulacs/pytket/extensions/qulacs/backends/qulacs_backend.py
- modules/pytket-qulacs/setup.py
- modules/pytket-stim/setup.py
Main change is that this release candidate includes RV3.
> [infra] Update pytket version to 1.0.0rc12

- .github/workflows/build-test
- .github/workflows/build_and_test.yml
- .github/workflows/hotfix.yml
Tested [here](https://github.com/CQCL/pytket-extensions/runs/5317576233).
> Use `python -m build` to build extensions.

- modules/pytket-honeywell/tests/api_test.py
- modules/pytket-honeywell/tests/api_test1.py
Otherwise pytest hangs on the CI with MacOS and Python 3.10.
> Move new test into separate file.

- modules/pytket-qsharp/_metadata.py
- modules/pytket-qsharp/docs/changelog.rst
- modules/pytket-qsharp/setup.py
> Update to qsharp 0.23.

- modules/pytket-braket/docs/changelog.rst
- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
> Fix readout errors for Rigetti devices

- modules/pytket-braket/docs/changelog.rst
- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
- modules/pytket-braket/setup.py
- modules/pytket-braket/tests/backend_test.py
> [pytket-braket] Support for local density-matrix and remote tensor-network simulators, with tests

- modules/pytket-braket/docs/changelog.rst
- modules/pytket-qiskit/pytket/extensions/qiskit/qiskit_convert.py
- modules/pytket-qiskit/tests/backend_test.py
- modules/pytket-qiskit/tests/qiskit_convert_test.py
> Fix two-qubit unitary conversion.

- .github/workflows/build_and_test.yml
- .github/workflows/docs.yml
- .github/workflows/hotfix.yml
- modules/pytket-qsharp/README.md
- modules/pytket-qsharp/_metadata.py
- modules/pytket-qsharp/docs/changelog.rst
- modules/pytket-qsharp/docs/intro.txt
- modules/pytket-qsharp/setup.py
> Update to qsharp 0.24 and dotnet 6.0

- modules/pytket-braket/docs/changelog.rst
- modules/pytket-qiskit/docs/changelog.rst
> Move changelog entry to the right extension module.

- modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/api_wrappers.py
> Ignore possible error from `nest_asyncio.apply()`

- .github/CODEOWNERS
- README.md
- modules/pytket-pysimplex/MANIFEST.in
- modules/pytket-pysimplex/README.md
- modules/pytket-pysimplex/_metadata.py
- modules/pytket-pysimplex/docs/api.rst
- modules/pytket-pysimplex/docs/changelog.rst
- modules/pytket-pysimplex/docs/intro.txt
- modules/pytket-pysimplex/pytket/extensions/pysimplex/__init__.py
- modules/pytket-pysimplex/pytket/extensions/pysimplex/backends/__init__.py
- modules/pytket-pysimplex/pytket/extensions/pysimplex/backends/simplex_backend.py
- modules/pytket-pysimplex/setup.py
- modules/pytket-pysimplex/tests/test-requirements.txt
- modules/pytket-pysimplex/tests/test_simplex.py
Basically an alternative to pytket-stim, optimized for large sparse circuits.
> Initial drop of pytket-pysimplex.

- modules/pytket-qiskit/docs/changelog.rst
- modules/pytket-qiskit/setup.py
> [pytket-qiskit] Update to qiskit 0.36

- modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py
Related to #381  added a sampling of results to pytket-ionq as @cqc-alec  mentioned.
Please let me know if changes are needed.
Thanks!
> [pytket-ionq] get sample counts by sampling from probability histogram

- modules/pytket-braket/pytket/extensions/braket/backends/braket.py
Related to Rigetti issue in #382 see Rigetti example for details in issue.
> [pytket-braket] fix backend measure index map for rigetti case

- modules/pytket-braket/docs/api.rst
Added tk_to_braket and braket_to_tk functions to API documentation.
> added bkconvert to API ref

- modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py
- modules/pytket-quantinuum/tests/api1_test.py
- modules/pytket-quantinuum/tests/backend_test.py
- modules/pytket-quantinuum/tests/conftest.py
> [pytket-quantinuum] Use new /machine api fields

- modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py
> update doc build

- modules/pytket-cirq/_metadata.py
- modules/pytket-cirq/docs/changelog.rst
- modules/pytket-cirq/pytket/extensions/cirq/backends/cirq.py
- modules/pytket-cirq/pytket/extensions/cirq/cirq_convert.py
- modules/pytket-cirq/setup.py
> [pytket-cirq] Update to cirq 0.15.

- modules/pytket-ionq/_metadata.py
- modules/pytket-ionq/docs/changelog.rst
- modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py
> [pytket-ionq] Change default device name.

- .github/workflows/docs/build-docs
- README.md
add link to new pytket-qujax docs
> add pytket-qujax to docs

- modules/pytket-quantinuum/docs/changelog.rst
- modules/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py
- modules/pytket-quantinuum/tests/api1_test.py
- modules/pytket-quantinuum/tests/backend_test.py
~blocked by #450 , review only the final commit~
> [feature][pytket-quantinuum] new direct submit_qasm method

- modules/pytket-iqm/tests/backend_test.py
disable remote tests temporarily
> [pytket-iqm] disable iqm tests

- modules/pytket-aqt/README.md
- modules/pytket-braket/README.md
- modules/pytket-cirq/README.md
- modules/pytket-ionq/README.md
- modules/pytket-iqm/README.md
- modules/pytket-projectq/README.md
- modules/pytket-pyquil/README.md
- modules/pytket-pysimplex/README.md
- modules/pytket-pyzx/README.md
- modules/pytket-qiskit/README.md
- modules/pytket-qsharp/README.md
- modules/pytket-qulacs/README.md
- modules/pytket-stim/README.md
Fix old pytket link in the readme of the extensions.
> fix link in readme

- modules/pytket-aqt/docs/intro.txt
- modules/pytket-cirq/docs/intro.txt
- modules/pytket-ionq/docs/intro.txt
- modules/pytket-projectq/docs/intro.txt
- modules/pytket-pyquil/docs/intro.txt
- modules/pytket-pysimplex/docs/intro.txt
- modules/pytket-pyzx/docs/intro.txt
- modules/pytket-qiskit/docs/intro.txt
- modules/pytket-qsharp/docs/intro.txt
- modules/pytket-qulacs/docs/intro.txt
- modules/pytket-stim/docs/intro.txt
Update logo in extensions docs with temporary workaround.
> update logos with workaround

- .github/workflows/docs/intro.txt
I have made some changes to the wording of this page and added some more text.
I have also resized the logo to be consistent with the rest of the docs.
Let me know if further changes to the wording are needed.
> Landing page update

- dev-utils/generate_mgit.sh
> add script for file renaming
